'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ShieldCheck } from 'lucide-react';
import { api } from '@/lib/api';
import { useAuth } from '@/components/providers';
import { Button } from '@/components/ui/primitives';

export default function LoginPage() {
  const router = useRouter(); const { signIn } = useAuth(); const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [displayName, setDisplayName] = useState(''); const [totpCode, setTotpCode] = useState(''); const [requiresTotp, setRequiresTotp] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { if (mode === 'register') { await api.register({ email, password, displayName }); } const tokens = await api.login({ email, password, totpCode: requiresTotp ? totpCode : undefined }); signIn(tokens); router.replace('/'); } catch (cause) { const message = cause instanceof Error ? cause.message : 'Authentication failed.'; setError(message); if (message.toLowerCase().includes('2fa required')) setRequiresTotp(true); } finally { setLoading(false); } }
  return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-brand-black p-5 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_10%_10%,rgba(34,211,238,.1),transparent_25%),radial-gradient(circle_at_90%_90%,rgba(139,92,246,.1),transparent_30%)]"/><section className="relative w-full max-w-md border border-white/10 bg-[#0b0b0d]/90 p-7 shadow-2xl backdrop-blur md:p-9"><div className="flex items-center gap-3"><div className="rounded-xl bg-white p-2 text-black"><ShieldCheck className="h-5 w-5"/></div><div><p className="font-serif text-2xl">OSINT Workbench</p><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Authorized analysts only</p></div></div><h1 className="mt-10 font-serif text-4xl">{mode === 'login' ? 'Welcome back.' : 'Create analyst account.'}</h1><p className="mt-3 text-sm leading-6 text-brand-gray-200">{mode === 'login' ? requiresTotp ? 'Enter the current code from your authenticator app.' : 'Sign in to access investigations and public-source intelligence.' : 'Accounts are subject to your organization’s investigation policy.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode === 'register' && <input className="field" placeholder="Display name" value={displayName} onChange={e => setDisplayName(e.target.value)} required/>}<input className="field" type="email" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} required/><input className="field" type="password" minLength={8} placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required/>{requiresTotp && <input className="field font-mono tracking-[.5em]" type="text" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="000000" value={totpCode} onChange={e => setTotpCode(e.target.value.replace(/\D/g, ''))} required autoFocus/>}{error && <p className="rounded-lg border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-100">{error}</p>}<Button className="w-full" type="submit" loading={loading}>{mode === 'login' ? requiresTotp ? 'Verify code' : 'Sign in' : 'Create account'}</Button></form><button className="mt-6 text-xs text-brand-gray-200 underline hover:text-white" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); setRequiresTotp(false); setTotpCode(''); }}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></section></main>;
}
