'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Database, FolderSearch, Radar } from 'lucide-react';
import { api } from '@/lib/api';
import { EmptyState, QueryError, Skeleton } from '@/components/ui/primitives';

export default function Home() {
  const investigations = useQuery({ queryKey: ['investigations'], queryFn: () => api.investigations('?limit=6') });
  const items = investigations.data?.items ?? [];
  const totals = items.reduce((acc, item) => ({ entities: acc.entities + item.counts.entities, findings: acc.findings + item.counts.findings, alerts: acc.alerts + item.counts.alerts }), { entities: 0, findings: 0, alerts: 0 });
  const metrics = [{ label: 'Open cases', value: items.filter(x => !['CLOSED', 'ARCHIVED'].includes(x.status)).length, icon: FolderSearch }, { label: 'Entities in view', value: totals.entities, icon: Database }, { label: 'Findings to triage', value: totals.findings, icon: Radar }];
  return <div className="animate-fade-up space-y-8 pb-12"><section className="border-b border-white/10 pb-9"><div className="flex flex-wrap items-center justify-between gap-4"><p className="eyebrow">Operations desk / active workspace</p><span className="font-mono text-[10px] uppercase tracking-wider text-brand-gray-200">Evidence-led · access controlled</span></div><div className="mt-6 flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><h1 className="title-serif text-4xl leading-[.95] md:text-6xl">Know the source.<br />Keep the chain.</h1><p className="mt-5 max-w-xl text-sm leading-6 text-brand-gray-200">Public-source research, provenance and case context in one disciplined workspace.</p></div><Link href="/intelligence" className="inline-flex items-center justify-center gap-2 border border-amber-300 bg-amber-300 px-5 py-3 text-[11px] font-bold uppercase tracking-[.12em] text-[#101817] transition hover:bg-amber-200">New query <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section className="grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-3">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="bg-[#162020] p-6"><Icon className="h-5 w-5 text-amber-200"/><p className="mt-8 font-mono text-4xl">{investigations.isLoading ? '—' : value}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">{label}</p></div>)}</section>
    <section className="glass-panel p-6 md:p-8"><div className="flex items-end justify-between border-b border-white/10 pb-5"><div><p className="eyebrow">Recent work</p><h2 className="title-serif mt-1 text-3xl">Investigations</h2></div><Link href="/investigations" className="text-[11px] font-bold uppercase tracking-wider text-amber-200 hover:text-amber-100">View all →</Link></div>{investigations.isLoading && <div className="mt-7 space-y-3">{[1,2,3].map(x => <Skeleton key={x} className="h-20"/>)}</div>}{investigations.isError && <div className="mt-7"><QueryError error={investigations.error}/></div>}{!investigations.isLoading && !investigations.isError && !items.length && <div className="mt-7"><EmptyState title="No investigations yet" description="Create a case first, then start gathering intelligence within its context." action={<Link href="/investigations" className="text-xs font-bold uppercase tracking-widest underline">Create investigation</Link>}/></div>}{items.length > 0 && <div className="mt-3 divide-y divide-white/10">{items.map(item => <Link href={`/investigations/${item.id}`} key={item.id} className="group flex items-center justify-between gap-4 py-5 transition hover:bg-black/10"><div><p className="text-sm font-medium group-hover:text-amber-100">{item.title}</p><p className="mt-1 font-mono text-[11px] text-brand-gray-200">{item.counts.entities} entities · {item.counts.findings} findings · updated {new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(item.updatedAt))}</p></div><ArrowRight className="h-4 w-4 text-brand-gray-200 transition group-hover:translate-x-1 group-hover:text-amber-200"/></Link>)}</div>}</section>
  </div>;
}
