'use client';

import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Database, FolderSearch, Radar } from 'lucide-react';
import { api } from '@/lib/api';
import { EmptyState, QueryError, Skeleton } from '@/components/ui/primitives';

export default function Home() {
  const investigations = useQuery({ queryKey: ['investigations'], queryFn: () => api.investigations('?limit=6') });
  const items = investigations.data?.items ?? [];
  const totals = items.reduce((acc, item) => ({ entities: acc.entities + item.counts.entities, findings: acc.findings + item.counts.findings, alerts: acc.alerts + item.counts.alerts }), { entities: 0, findings: 0, alerts: 0 });
  const metrics = [{ label: 'Open cases', value: items.filter(x => !['CLOSED', 'ARCHIVED'].includes(x.status)).length, icon: FolderSearch }, { label: 'Entities in view', value: totals.entities, icon: Database }, { label: 'Findings to triage', value: totals.findings, icon: Radar }];
  return <div className="animate-fade-up space-y-8 pb-12"><section className="glass-panel overflow-hidden p-8 md:p-10"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-cyan-200">Investigation command center</p><div className="mt-5 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><h1 className="title-serif text-4xl md:text-5xl">Start from a fact.<br />Build a defensible case.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-brand-gray-200">Search public-source intelligence, retain the provenance of every finding, and turn isolated indicators into a navigable case.</p></div><Link href="/intelligence" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-bold uppercase tracking-widest text-black">New intelligence query <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section className="grid gap-4 md:grid-cols-3">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="glass-panel p-6"><Icon className="h-5 w-5 text-brand-gray-100"/><p className="mt-7 text-3xl font-medium">{investigations.isLoading ? '—' : value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">{label}</p></div>)}</section>
    <section className="glass-panel p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Recent work</p><h2 className="title-serif mt-2 text-3xl">Investigations</h2></div><Link href="/investigations" className="text-xs text-brand-gray-100 hover:text-white">View all →</Link></div>{investigations.isLoading && <div className="mt-7 space-y-3">{[1,2,3].map(x => <Skeleton key={x} className="h-20"/>)}</div>}{investigations.isError && <div className="mt-7"><QueryError error={investigations.error}/></div>}{!investigations.isLoading && !investigations.isError && !items.length && <div className="mt-7"><EmptyState title="No investigations yet" description="Create a case first, then start gathering intelligence within its context." action={<Link href="/investigations" className="text-xs font-bold uppercase tracking-widest underline">Create investigation</Link>}/></div>}{items.length > 0 && <div className="mt-7 divide-y divide-white/5">{items.map(item => <Link href={`/investigations/${item.id}`} key={item.id} className="flex items-center justify-between gap-4 py-4 transition hover:bg-white/[.02]"><div><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-brand-gray-200">{item.counts.entities} entities · {item.counts.findings} findings · updated {new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(item.updatedAt))}</p></div><ArrowRight className="h-4 w-4 text-brand-gray-200"/></Link>)}</div>}</section>
  </div>;
}
