'use client';

import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { ExternalLink, FileSearch, Network } from 'lucide-react';
import { api } from '@/lib/api';
import { Badge, EmptyState, QueryError, SeverityBadge, Skeleton } from '@/components/ui/primitives';

export default function EntityDossierPage() {
  const params = useParams<{ id: string }>();
  const dossier = useQuery({ queryKey: ['entity', params.id], queryFn: () => api.entity(params.id) });
  if (dossier.isLoading) return <div className="space-y-5"><Skeleton className="h-40"/><Skeleton className="h-80"/></div>;
  if (dossier.isError) return <QueryError error={dossier.error}/>;
  if (!dossier.data) return <EmptyState title="Entity unavailable" description="The entity may have been removed or you may no longer have access to this investigation."/>;
  const data = dossier.data;
  return <div className="mx-auto max-w-6xl animate-fade-up pb-12"><header className="border-b border-white/10 pb-7"><div className="flex flex-wrap items-center gap-3"><Badge value={data.entity.kind}/><span className="text-xs text-brand-gray-200">Canonical intelligence record</span></div><h1 className="mt-4 break-all font-mono text-3xl text-white md:text-5xl">{data.entity.value}</h1><div className="mt-5 flex flex-wrap gap-6 text-sm text-brand-gray-200"><span>Risk score <b className="text-white">{data.entity.riskScore.toFixed(1)}</b></span><span>Last enriched <b className="text-white">{data.entity.lastEnrichedAt ? new Date(data.entity.lastEnrichedAt).toLocaleString() : 'Never'}</b></span></div></header>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="glass-panel p-6"><div className="flex items-center gap-3"><FileSearch className="h-5 w-5 text-cyan-200"/><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Analyst findings</p><h2 className="title-serif mt-1 text-3xl">Evidence-backed signals</h2></div></div>{data.findings.length === 0 ? <div className="mt-6"><EmptyState title="No findings yet" description="A provider may have no data, or enrichment may still be in progress."/></div> : <div className="mt-6 space-y-3">{data.findings.map(finding => <article key={finding.id} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><SeverityBadge severity={finding.severity}/><span className="text-[10px] uppercase tracking-widest text-brand-gray-200">{finding.source} · {Math.round(finding.confidence * 100)}% confidence</span></div><h3 className="mt-4 font-medium">{finding.title}</h3><p className="mt-2 text-sm leading-6 text-brand-gray-200">{finding.description}</p><div className="mt-3 flex items-center justify-between text-xs text-brand-gray-200"><span>Observed {new Date(finding.observedAt).toLocaleString()}</span>{finding.sourceUrl && <a href={finding.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-cyan-100 hover:text-white">Source <ExternalLink className="h-3 w-3"/></a>}</div></article>)}</div>}</section>
      <aside className="space-y-5"><section className="glass-panel p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Provider runs</p><div className="mt-4 space-y-3">{data.results.length === 0 ? <p className="text-sm text-brand-gray-200">No provider result stored yet.</p> : data.results.map(result => <div key={result.id} className="flex items-center justify-between gap-3 border-b border-white/5 pb-3 last:border-0 last:pb-0"><div><p className="text-sm">{result.provider}</p><p className="mt-1 text-xs text-brand-gray-200">{result.durationMs}ms · {new Date(result.fetchedAt).toLocaleString()}</p></div><Badge value={result.status}/></div>)}</div></section><section className="glass-panel p-5"><div className="flex items-center gap-2"><Network className="h-4 w-4 text-violet-200"/><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Relations</p></div><div className="mt-4 space-y-3">{data.relations.length === 0 ? <p className="text-sm text-brand-gray-200">No source-supported relationships yet.</p> : data.relations.map(relation => <div key={relation.id} className="border-l border-violet-300/40 pl-3"><p className="text-sm">{relation.relation.replaceAll('_', ' ')}</p><p className="mt-1 text-xs text-brand-gray-200">{relation.sourceName} · {Math.round(relation.confidence * 100)}% confidence</p></div>)}</div></section></aside></div>
  </div>;
}
