import { CalendarClock, CornerDownRight } from 'lucide-react';
import { ApiError, TimelineEvent } from '@/lib/api';
import { Skeleton } from '@/components/ui/primitives';

interface Props { events?: TimelineEvent[]; loading?: boolean; error?: Error | null; }
const tone = (event: TimelineEvent) => event.severity === 'CRITICAL' || event.severity === 'HIGH' ? '#ef7c72' : event.severity === 'MEDIUM' ? '#efb566' : '#62adff';

export function CaseTimeline({ events, loading, error }: Props) {
  const unavailable = error instanceof ApiError && error.status === 404;
  return <section className="mt-10 border-t border-[#354256] pt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Chronology</p><h2 className="title-serif mt-2 text-4xl">Case timeline</h2><p className="mt-3 text-sm text-[#9dafc6]">Observations and analyst actions, normalised to UTC.</p></div><CalendarClock className="h-5 w-5 text-[#62adff]"/></div>{loading && <div className="mt-6 border border-[#354256]">{[1,2,3].map(item => <Skeleton key={item} className="h-16 border-b border-[#354256] last:border-0"/>)}</div>}{unavailable && <div className="mt-6 border-l-2 border-[#efb566] bg-[#2b251c] p-4 text-sm text-[#d8c79f]"><b className="text-[#f0d28b]">Timeline feed is not deployed.</b><p className="mt-1">The workbench will show real events when the case timeline endpoint becomes available.</p></div>}{!loading && !error && !events?.length && <p className="mt-6 border border-[#354256] p-5 text-sm text-[#9dafc6]">No event has been recorded for this case.</p>}{events?.length ? <ol className="mt-6 border border-[#354256]">{events.map((event, index) => <li className="grid grid-cols-[78px_1fr] border-b border-[#354256] last:border-0" key={event.id}><time className="border-r border-[#354256] px-4 py-5 font-mono text-[10px] text-[#7d9ec5]">{new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(event.occurredAt))}</time><div className="relative p-5"><i className="absolute -left-[5px] top-[25px] h-2.5 w-2.5" style={{ background: tone(event) }}/><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[#e5edf7]">{event.title}</p><span className="font-mono text-[9px] uppercase tracking-wider text-[#7e91ac]">{event.kind}</span></div>{event.summary && <p className="mt-2 text-sm leading-6 text-[#a7b7cb]">{event.summary}</p>}<p className="mt-3 flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-[#8295b1]"><CornerDownRight className="h-3.5 w-3.5"/>{event.source || event.actor?.displayName || `Record ${index + 1}`}</p></div></li>)}</ol> : null}{!unavailable && !!error && <p className="mt-6 border-l-2 border-red-400 p-4 text-sm text-red-200">Timeline could not be loaded: {error.message}</p>}</section>;
}
