import { cn } from '@/lib/utils';
import { AlertCircle, Loader2 } from 'lucide-react';
import { ApiError } from '@/lib/api';

export function Button({ className, loading, children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) {
  return <button className={cn('inline-flex items-center justify-center gap-2 border border-[#62adff] bg-[#62adff] px-4 py-2.5 text-[11px] font-bold uppercase tracking-[0.12em] text-[#0e1724] transition hover:bg-[#8bc4ff] disabled:cursor-not-allowed disabled:opacity-45', className)} disabled={loading || props.disabled} {...props}>{loading && <Loader2 className="h-4 w-4 animate-spin" />}{children}</button>;
}
export function Badge({ value, className }: { value: string; className?: string }) { return <span className={cn('inline-flex border border-white/15 bg-black/10 px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-brand-gray-100', className)}>{value.replaceAll('_', ' ')}</span>; }
export function SeverityBadge({ severity }: { severity: string }) { const colors: Record<string, string> = { CRITICAL: 'border-red-400/40 bg-red-500/10 text-red-300', HIGH: 'border-[#ef8074]/50 bg-[#ef8074]/10 text-[#ffafa6]', MEDIUM: 'border-[#efb566]/50 bg-[#efb566]/10 text-[#f5cd8b]', LOW: 'border-[#62adff]/50 bg-[#62adff]/10 text-[#9acbff]', INFO: 'border-[#53647e] bg-[#1c2738] text-[#b2c0d2]' }; return <Badge value={severity} className={colors[severity]}/>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="border border-[#354256] bg-[#131c2a] flex min-h-64 flex-col items-center justify-center px-6 text-center"><div className="mb-4 border border-[#45628b] bg-[#162338] p-3"><AlertCircle className="h-5 w-5 text-[#62adff]" /></div><h2 className="title-serif text-2xl">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-[#9dafc6]">{description}</p>{action && <div className="mt-6">{action}</div>}</div>; }
export function QueryError({ error }: { error: Error }) { const apiError = error instanceof ApiError ? error : null; return <div role="alert" className="border border-red-400/35 bg-red-500/10 p-5 text-sm text-red-100"><p className="font-bold">Couldn’t load this data</p><p className="mt-1 text-red-100/75">{error.message}</p>{apiError && <p className="mt-3 font-mono text-[10px] text-red-100/60">{apiError.code}{apiError.correlationId ? ` · reference ${apiError.correlationId}` : ''}</p>}</div>; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn('animate-pulse bg-white/5', className)} />; }
