'use client';

import { useQuery } from '@tanstack/react-query';
import { KeyRound, ShieldCheck, Wifi } from 'lucide-react';
import { api } from '@/lib/api';
import { Badge, QueryError, Skeleton } from '@/components/ui/primitives';

export default function SourceControlPage() {
  const providers = useQuery({ queryKey: ['providers'], queryFn: api.providers });
  return <div className="animate-fade-up"><header className="border-b border-[#354256] pb-9"><p className="eyebrow">System settings / source control</p><h1 className="title-serif mt-4 text-5xl sm:text-6xl">Source control</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#aebbd0]">Availability and scope of intelligence providers. Secrets are configured only in protected server-side deployment settings.</p></header><div className="mt-9 grid gap-10 xl:grid-cols-[1.2fr_.8fr]"><section><div className="flex items-end justify-between border-b border-[#354256] pb-4"><div><p className="eyebrow">Provider registry</p><h2 className="title-serif mt-2 text-4xl">Operational sources</h2></div><Wifi className="h-5 w-5 text-[#62adff]"/></div>{providers.isLoading && <div className="mt-5 border border-[#354256]">{[1,2,3,4].map(item => <Skeleton className="h-20 border-b border-[#354256] last:border-0" key={item}/>)}</div>}{providers.isError && <div className="mt-5"><QueryError error={providers.error}/></div>}{providers.data && <div className="mt-5 border border-[#354256]"><div className="grid grid-cols-[1fr_150px_110px] border-b border-[#354256] bg-[#131c2a] px-5 py-3 font-mono text-[9px] uppercase tracking-[.16em] text-[#7185a3]"><span>Source</span><span>Entity scope</span><span>State</span></div>{providers.data.map(source => <article className="grid grid-cols-[1fr_150px_110px] items-center border-b border-[#354256] px-5 py-5 last:border-0" key={source.name}><div><p className="text-sm text-[#e4edf8]">{source.displayName}</p><p className="mt-2 text-xs text-[#8fa1ba]">{source.freeTier || 'Usage terms held by provider'}</p></div><p className="font-mono text-[10px] uppercase tracking-wider text-[#8da1bd]">{source.supports.slice(0, 3).join(', ')}</p><Badge value={source.enabled ? source.status || 'READY' : 'DISABLED'}/></article>)}</div>}</section><aside className="space-y-6"><section className="border-l-2 border-[#62adff] bg-[#182130] p-6"><KeyRound className="h-5 w-5 text-[#62adff]"/><p className="eyebrow mt-7">Credential boundary</p><h2 className="title-serif mt-2 text-3xl">Secrets do not enter the browser.</h2><p className="mt-4 text-sm leading-7 text-[#a9b8ca]">Keys are never returned through this API or stored in the analyst workspace.</p></section><section className="border-l-2 border-[#61d6a0] bg-[#182130] p-6"><ShieldCheck className="h-5 w-5 text-[#61d6a0]"/><p className="eyebrow mt-7">Access boundary</p><h2 className="title-serif mt-2 text-3xl">Results remain case-scoped.</h2><p className="mt-4 text-sm leading-7 text-[#a9b8ca]">Provider outputs, evidence and updates follow investigation access control.</p></section></aside></div></div>;
}
