'use client';

import { ChangeEvent, useState } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'next/navigation';
import { FileUp, FolderOpen, Hash } from 'lucide-react';
import { api } from '@/lib/api';
import { Badge, Button, EmptyState, QueryError, Skeleton } from '@/components/ui/primitives';
const OsintGraph = dynamic(() => import('@/components/dashboard/graph/osint-graph').then(module => module.OsintGraph), { ssr: false, loading: () => <Skeleton className="h-full"/> });

export default function InvestigationWorkbench() {
  const { id } = useParams<{ id: string }>(); const client = useQueryClient(); const [file, setFile] = useState<File | null>(null);
  const investigation = useQuery({ queryKey: ['investigation', id], queryFn: () => api.investigation(id) });
  const entities = useQuery({ queryKey: ['case-entities', id], queryFn: () => api.caseEntities(id) });
  const evidence = useQuery({ queryKey: ['evidence', id], queryFn: () => api.evidence(id) });
  const graph = useQuery({ queryKey: ['graph', id], queryFn: () => api.graph(id) });
  const upload = useMutation({ mutationFn: (target: File) => api.uploadEvidence(id, target), onSuccess: () => { client.invalidateQueries({ queryKey: ['evidence', id] }); setFile(null); } });
  if (investigation.isLoading) return <div className="space-y-5"><Skeleton className="h-36"/><Skeleton className="h-96"/></div>; if (investigation.isError) return <QueryError error={investigation.error}/>; if (!investigation.data) return <EmptyState title="Case unavailable" description="This investigation may not exist or may no longer be accessible."/>;
  const item = investigation.data;
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { setFile(event.target.files?.[0] ?? null); }
  return <div className="mx-auto max-w-7xl animate-fade-up pb-12"><header className="border-b border-white/10 pb-7"><div className="flex flex-wrap items-center gap-3"><Badge value={item.status}/>{item.tags.map(tag => <span className="text-xs text-brand-gray-200" key={tag}>#{tag}</span>)}</div><h1 className="title-serif mt-4 text-4xl md:text-5xl">{item.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-brand-gray-200">{item.description || 'No case description yet.'}</p></header>
    <div className="mt-7 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><section className="glass-panel p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Entities</p><h2 className="title-serif mt-1 text-3xl">Working set</h2></div><Link className="text-xs font-bold uppercase tracking-widest text-cyan-100 hover:text-white" href="/intelligence">Add indicator</Link></div>{entities.isLoading && <div className="mt-6 space-y-3"><Skeleton className="h-16"/><Skeleton className="h-16"/></div>}{entities.isError && <div className="mt-6"><QueryError error={entities.error}/></div>}{!entities.isLoading && !entities.isError && !(entities.data?.items.length) && <div className="mt-6"><EmptyState title="No entities yet" description="Add an indicator through Intelligence to begin a source-aware enrichment."/></div>}{entities.data?.items.length ? <div className="mt-6 divide-y divide-white/5">{entities.data.items.map(caseEntity => <Link key={caseEntity.id} href={`/entities/${caseEntity.entity.id}`} className="flex items-center justify-between gap-4 py-4 hover:bg-white/[.02]"><div className="min-w-0"><Badge value={caseEntity.entity.kind}/><p className="mt-2 truncate font-mono text-sm">{caseEntity.entity.value}</p></div><span className="text-xs text-brand-gray-200">risk {caseEntity.entity.riskScore.toFixed(1)}</span></Link>)}</div> : null}</section>
      <aside className="glass-panel p-6"><div className="flex items-center gap-3"><FolderOpen className="h-5 w-5 text-violet-200"/><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Case scope</p><p className="mt-1 text-sm">{item.owner.displayName}</p></div></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-brand-gray-200">Entities</dt><dd className="mt-1 text-xl">{item.counts.entities}</dd></div><div><dt className="text-brand-gray-200">Findings</dt><dd className="mt-1 text-xl">{item.counts.findings}</dd></div><div><dt className="text-brand-gray-200">Evidence</dt><dd className="mt-1 text-xl">{item.counts.evidence}</dd></div><div><dt className="text-brand-gray-200">Alerts</dt><dd className="mt-1 text-xl">{item.counts.alerts}</dd></div></dl></aside></div>
    <section className="glass-panel mt-5 p-6"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">File intelligence</p><h2 className="title-serif mt-1 text-3xl">Evidence & metadata</h2><p className="mt-2 max-w-2xl text-sm text-brand-gray-200">Extract hashes and document or photo metadata in an isolated backend worker. Original files stay access-controlled.</p></div><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-xs font-bold uppercase tracking-widest transition hover:border-white/35"><FileUp className="h-4 w-4"/>Choose file<input type="file" className="sr-only" onChange={chooseFile}/></label></div>{file && <div className="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-cyan-300/25 bg-cyan-300/5 p-4"><div><p className="text-sm">{file.name}</p><p className="mt-1 text-xs text-brand-gray-200">{(file.size / 1024 / 1024).toFixed(2)} MB · upload triggers safe metadata extraction</p></div><Button loading={upload.isPending} onClick={() => upload.mutate(file)}>Analyze file</Button></div>}{upload.isError && <div className="mt-4"><QueryError error={upload.error}/></div>}{evidence.data?.items.length ? <div className="mt-6 grid gap-3 md:grid-cols-2">{evidence.data.items.map(item => <article key={item.id} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm">{item.title}</p><p className="mt-1 text-xs text-brand-gray-200">{item.analysis?.detectedMime || item.mimeType || 'Detecting file type'} · {item.analysis?.status || 'QUEUED'}</p></div><Hash className="h-4 w-4 text-brand-gray-200"/></div>{item.analysis?.sha256 || item.sha256 ? <p className="mt-3 truncate font-mono text-[10px] text-cyan-100">SHA-256 {item.analysis?.sha256 || item.sha256}</p> : <p className="mt-3 text-xs text-brand-gray-200">Integrity hash will appear after analysis.</p>}</article>)}</div> : !evidence.isLoading && <p className="mt-6 text-sm text-brand-gray-200">No evidence uploaded to this case.</p>}</section>
    <section className="glass-panel mt-5 p-6"><p className="text-[10px] font-bold uppercase tracking-widest text-brand-gray-200">Relationship graph</p><h2 className="title-serif mt-1 text-3xl">Case connections</h2>{graph.isError ? <p className="mt-4 text-sm text-brand-gray-200">The saved graph is currently unavailable.</p> : !graph.data?.nodes.length ? <p className="mt-4 text-sm text-brand-gray-200">No saved graph nodes yet. Relationships discovered during enrichment will appear here.</p> : <div className="mt-5 h-[480px]"><OsintGraph elements={[...graph.data.nodes.map(node => ({ data: { id: node.id, label: node.label, kind: node.kind } })), ...graph.data.edges.map(edge => ({ data: { id: edge.id || `${edge.source}-${edge.target}-${edge.relation}`, source: edge.source, target: edge.target, relation: edge.relation } }))]}/></div>}</section>
  </div>;
}
